services:
  cart-service-query-db:
    image: mongo:7
    container_name: cart-service-db
    restart: unless-stopped
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    volumes:
      - mongodb:/data/db

  cart-service-command-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: carts
    ports:
      - 5434:5432
    volumes:
      - postgres:/var/lib/postgresql


volumes:
  mongodb:
  postgres: