services:
  cart-service-db:
    image: mongo:7
    container_name: cart-service-db
    restart: unless-stopped
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
